spring.application.name=E-Mart
spring.datasource.url=jdbc:mysql://localhost:3306/emart
spring.datasource.username=root
spring.datasource.password=Aman@6940
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Single file max size
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB




# Total request size (all files + JSON)
spring.servlet.multipart.max-request-size=100MB
server.tomcat.threads.max=300
server.tomcat.threads.min-spare=50
logging.level.org.springframework.security=DEBUG

