spring.application.name=E-Mart
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/emart}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Aman@6940}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Single file max size
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

server.tomcat.threads.max=300
server.tomcat.threads.min-spare=50
logging.level.org.springframework.security=DEBUG

# Spring Mail SMTP Config (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:yadavaman6940@gmail.com}
spring.mail.password=${MAIL_PASSWORD:nldbazvvwrqbazqu}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=6000
spring.mail.properties.mail.smtp.timeout=6000
spring.mail.properties.mail.smtp.writetimeout=6000
